name: Generate CSV
on:
  workflow_dispatch:

jobs:
  run-commands:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install dependencies
        working-directory: packages/yoastseo
        run: yarn install --ignore-scripts
        
       # Check directory permissions
      - name: Check directory permissions
        run: ls -l /home/runner/work/wordpress-seo/wordpress-seo

      # Check node version
      - name: Check node version
        run: node -v 

      # Run tests with debug logs
      - name: Run tests
        working-directory: packages/yoastseo
        run: yarn export:inclusive-language
