name: Generate CSV
on:
  workflow_dispatch:

jobs:
  run-commands:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Set up dependencies for building native modules
      - name: Set up dependencies for building native modules
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3
        
       # Check directory permissions
      - name: Check directory permissions
        run: ls -ld packages/yoastseo 

      # Run tests
      - name: Run tests
        working-directory: packages/yoastseo
        run: yarn export:inclusive-language
